// signup
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
// login constants
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
//user token
export const USER_TOKEN = 'USER_TOKEN';
// user profile constants
export const FETCHING_USER_REQUEST = 'FETCHING_USER_REQUEST';
export const FETCHING_USER_SUCCESS = 'FETCHING_USER_SUCCESS';
export const FETCHING_USER_FAILURE = 'FETCHING_USER_FAILURE';
// CHATROOM constants
export const CREATING_CHATROOM_REQUEST = 'CREATING_CHATROOM_REQUEST';
export const CREATING_CHATROOM_SUCCESS = 'CREATING_CHATROOM_SUCCESS'; 
export const CREATING_CHATROOM_FAILURE = 'CREATING_CHATROOM_FAILURE';
export const FETCHING_CHATROOM_REQUEST = 'FETCHING_CHATROOM_REQUEST';
export const FETCHING_CHATROOM_SUCCESS = 'FETCHING_CHATROOM_SUCCESS'; 
export const FETCHING_CHATROOM_FAILURE = 'FETCHING_CHATROOM_FAILURE';
// CHATMESSAGE constants
export const CREATING_CHATMESSAGE_REQUEST = 'CREATING_CHATMESSAGE_REQUEST';
export const CREATING_CHATMESSAGE_SUCCESS = 'CREATING_CHATMESSAGE_SUCCESS'; 
export const CREATING_CHATMESSAGE_FAILURE = 'CREATING_CHATMESSAGE_FAILURE';
export const FETCHING_CHATMESSAGE_REQUEST = 'FETCHING_CHATMESSAGE_REQUEST';
export const FETCHING_CHATMESSAGE_SUCCESS = 'FETCHING_CHATMESSAGE_SUCCESS'; 
export const FETCHING_CHATMESSAGE_FAILURE = 'FETCHING_CHATMESSAGE_FAILURE';